name: Create Unity Package

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: 1.0.2
        name: Release 1.0.2
        body: 1.0.2
    - name: Find all meta files
      run: |
        echo "Assets/Scenes.meta" > metaList
        find Assets/Scenes/ -name \*.meta >> metaList
    - name: Make directory for our unity package
      run: mkdir a
    - name: Create Unity Package
      uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/DemoPackage.unitypackage'
        include-files: metaList
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: 'a/DemoPackage.unitypackage'
        tags: true
        draft: true